version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "rootpasswd"
      MYSQL_DATABASE: "av-superb-benchmark"
      MYSQL_USER: "av-superb"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
