version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: av-superb-dev-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "rootpasswd"
      MYSQL_DATABASE: "avsuperb"
      MYSQL_USER: "av-superb"
      MYSQL_PASSWORD: "mysqlpassword"
    ports:
      - "3306:3306"
