#Upload Related
UPLOAD_DIR: "./upload"

# Submission related
DAILY_SUBMIT_LIMIT: 1000
WEEKLY_SUBMIT_LIMIT: 1000

# Metrics related
UNZIP_TIMEOUT: "30s"
GROUND_TRUTH_ROOT: "./inference/truth/"

# Public
## Individual submission info
INDIVIDUAL_SUBMISSION_INFO:
    FILE:
        - aoeTimeUpload
        - task
        - showOnLeaderboard
        - submitName
        - modelURL
        - modelDesc
        - paramShared
        - state
        - stateInfo
        - submitUUID
    SCORE:
        - AS_20K
        - VGGSound
        - Kinetics_Sounds
        - UCF101
        - LRS3_TED
        - VoxCeleb2
        - IEMOCAP

## Leaderboard shown data
LEADERBOARD_INFO:
    FILE:
        - aoeTimeUpload
        - task
        - submitName
        - modelURL
        - modelDesc
        - paramShared
    SCORE:
        - AS_20K
        - VGGSound
        - Kinetics_Sounds
        - UCF101
        - LRS3_TED
        - VoxCeleb2
        - IEMOCAP

