#Upload Related
UPLOAD_DIR: "./upload"

# Submission related
DAILY_SUBMIT_LIMIT: 1000
WEEKLY_SUBMIT_LIMIT: 1000

# Metrics related
UNZIP_TIMEOUT: "30s"
GROUND_TRUTH_ROOT: "./inference/truth/"

# Public
## Individual submission info
INDIVIDUAL_SUBMISSION_INFO:
    FILE:
        - aoeTimeUpload
        - showOnLeaderboard
        - submitName
        - modelURL
        - modelDesc
        - paramShared
        - state
        - stateInfo
        - submitUUID
    SCORE:
        - track
        - AS_20K_map_public
        - VGGSound_acc_public
        - Kinetics_Sounds_acc_public
        - UCF101_acc_public
        - LRS3_TED_cer_public
        - VoxCeleb2_eer_public
        - IEMOCAP_acc_public

## Leaderboard shown data
LEADERBOARD_INFO:
    FILE:
        - aoeTimeUpload
        - submitName
        - modelURL
        - modelDesc
        - paramShared
    SCORE:
        - track
        - AS_20K_map_public
        - VGGSound_acc_public
        - Kinetics_Sounds_acc_public
        - UCF101_acc_public
        - LRS3_TED_cer_public
        - VoxCeleb2_eer_public
        - IEMOCAP_acc_public

