version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "v24avnq3owe52dav"
      MYSQL_DATABASE: "multi-modal-benchmark"
      MYSQL_USER: "mmb"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
